
package com.kangmei.cxf.service.factory;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IThirdOrderWSDL", targetNamespace = "http://factory.service.cxf.kangmei.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IThirdOrderWSDL {


    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "saveOrderInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrderInfo", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveOrderInfo")
    @ResponseWrapper(localName = "saveOrderInfoResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveOrderInfoResponse")
    public byte[] saveOrderInfo(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "saveCancelOrder")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveCancelOrder", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveCancelOrder")
    @ResponseWrapper(localName = "saveCancelOrderResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveCancelOrderResponse")
    public byte[] saveCancelOrder(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "getOrderInfoByOrderId")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrderInfoByOrderId", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.GetOrderInfoByOrderId")
    @ResponseWrapper(localName = "getOrderInfoByOrderIdResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.GetOrderInfoByOrderIdResponse")
    public byte[] getOrderInfoByOrderId(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @param characterSet
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "saveOrderInfoToCharacterSet")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveOrderInfoToCharacterSet", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveOrderInfoToCharacterSet")
    @ResponseWrapper(localName = "saveOrderInfoToCharacterSetResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveOrderInfoToCharacterSetResponse")
    public byte[] saveOrderInfoToCharacterSet(
        @WebParam(name = "request", targetNamespace = "")
        String request,
        @WebParam(name = "characterSet", targetNamespace = "")
        String characterSet);

    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "updateAccountInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateAccountInfo", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.UpdateAccountInfo")
    @ResponseWrapper(localName = "updateAccountInfoResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.UpdateAccountInfoResponse")
    public byte[] updateAccountInfo(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @param characterSet
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "saveCancelOrderToCharacterSet")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveCancelOrderToCharacterSet", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveCancelOrderToCharacterSet")
    @ResponseWrapper(localName = "saveCancelOrderToCharacterSetResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SaveCancelOrderToCharacterSetResponse")
    public byte[] saveCancelOrderToCharacterSet(
        @WebParam(name = "request", targetNamespace = "")
        String request,
        @WebParam(name = "characterSet", targetNamespace = "")
        String characterSet);

    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "updatePrescriptionBoilStatus")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updatePrescriptionBoilStatus", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.UpdatePrescriptionBoilStatus")
    @ResponseWrapper(localName = "updatePrescriptionBoilStatusResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.UpdatePrescriptionBoilStatusResponse")
    public byte[] updatePrescriptionBoilStatus(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns byte[]
     */
    @WebMethod(action = "cancelPrescription")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelPrescription", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.CancelPrescription")
    @ResponseWrapper(localName = "cancelPrescriptionResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.CancelPrescriptionResponse")
    public byte[] cancelPrescription(
        @WebParam(name = "request", targetNamespace = "")
        String request);

    /**
     * 
     * @param request
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "simpleRefundFun")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "simpleRefundFun", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SimpleRefundFun")
    @ResponseWrapper(localName = "simpleRefundFunResponse", targetNamespace = "http://factory.service.cxf.kangmei.com/", className = "com.kangmei.cxf.service.factory.SimpleRefundFunResponse")
    public String simpleRefundFun(
        @WebParam(name = "request", targetNamespace = "")
        String request);

}
